---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatapp-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatapp-frontend
  template:
    metadata:
      labels:
        app: chatapp-frontend
    spec:
      containers:
      - name: chatapp-frontend
        image: megakuul/chatapp:frontend
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: chatapp-frontend
spec:
  type: LoadBalancer
  selector:
    app: chatapp-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatapp-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatapp-api
  template:
    metadata:
      labels:
        app: chatapp-api
    spec:
      containers:
      - name: chatapp-api
        image: megakuul/chatapp:api
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: chatapp-api
spec:
  type: LoadBalancer
  selector:
    app: chatapp-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80